### ISSUE TITLE
Battery status

### ISSUE THREAD

**Issue by dima-fedotovs** [Xinyuan-LilyGO/T7-S3#6]
How to read battery status/voltage? I'm using ESPHome config:

```
sensor:
    - platform: adc
      id: battery_level
      pin: 2
```

And this sensor always shows the same value of 0.961 until it is switched off because empty battery. 
Is it possible to measure the voltage on pin 2?
